"""Generate the fixed Ma=2.25 isothermal compressible similarity inlet.

Dorodnitsyn coordinate: Y'=T, u=f', C=mu/T.
(C f'')'+f f''/2=0;
(C T'/Pr)'+f T'/2+(gamma-1) M^2 C f''^2=0.
The dimensional origin is selected so u(y/delta0=1)=0.99.
Requires numpy/scipy only for regeneration; the solver uses the saved table.
"""
from pathlib import Path
import json,argparse
import numpy as np
from scipy.integrate import solve_bvp, cumulative_trapezoid
from scipy.interpolate import PchipInterpolator

ROOT = Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('--output-directory',type=Path,default=ROOT/'cases/manual/case10_compression_ramp/reference')
parser.add_argument('--table',type=Path,default=ROOT/'include/wcns/physics/ramp_inlet_table.inc')
args=parser.parse_args()
M, PR, S, TW, RE = 2.25, .72, 110.4/170, 323/170, 15800

def ode(eta, q):
    f, u, a, t, b = q
    c = np.sqrt(t)*(1+S)/(t+S)
    dc = c*(.5/t-1/(t+S))*b
    return np.array([u, a, (-.5*f*a-dc*a)/c, b,
                     (-.5*PR*f*b-PR*.4*M*M*c*a*a-dc*b)/c])

eta=np.linspace(0,16,501)
u=np.tanh(eta/3)
q=np.array([3*np.log(np.cosh(eta/3)),u,(1-u*u)/3,
            1+(TW-1)*np.exp(-eta/3),-(TW-1)*np.exp(-eta/3)/3])
sol=solve_bvp(ode,lambda a,b:np.array([a[0],a[1],a[3]-TW,b[1]-1,b[3]-1]),
              eta,q,tol=1e-10,max_nodes=12000)
if not sol.success: raise RuntimeError(sol.message)
eta=np.linspace(0,16,20001)
f,u,_,t,_=sol.sol(eta)
Y=cumulative_trapezoid(t,eta,initial=0)
Y99=float(PchipInterpolator(u[u<.9999],Y[u<.9999])(.99))
y=Y/Y99
v=Y99/(2*RE)*(Y*u-t*f)
# Far above the layer, blend displacement flow to zero in y/delta0=[2,3].
v*=1-np.clip((y-2),0,1)**2*(3-2*np.clip(y-2,0,1))
grid=np.linspace(0,4,1025)
U=PchipInterpolator(y,u,extrapolate=False)(np.minimum(grid,y[-1]))
T=PchipInterpolator(y,t,extrapolate=False)(np.minimum(grid,y[-1]))
V=PchipInterpolator(y,v,extrapolate=False)(np.minimum(grid,y[-1]))
U[grid>=y[-1]]=1; T[grid>=y[-1]]=1; V[grid>=y[-1]]=0
rows=np.column_stack([grid,1/T,U,V,T])
dest=args.output_directory
dest.mkdir(parents=True,exist_ok=True)
np.savetxt(dest/'inlet_similarity.csv',rows,delimiter=',',header='y_delta0,rho,u,v,T',comments='')
(dest/'inlet_similarity.json').write_text(json.dumps(dict(Mach=M,Pr=PR,S_over_Tinf=S,
    Tw_over_Tinf=TW,Re_delta0=RE,Y99=Y99,bvp_max_rms_residual=float(max(sol.rms_residuals)),
    delta99_definition='u/Uinf=0.99',outer_v_blend='2<y/delta0<3'),indent=2)+'\n')
out=args.table
out.parent.mkdir(parents=True,exist_ok=True)
out.write_text('// Generated by tools/generate_ramp_inlet.py; u,v,T at y=n/256.\n'+
    '\n'.join('    {{'+','.join(f'{x:.17g}' for x in row)+'}},' for row in rows[:,2:])+'\n')
print('Similarity profile:', len(rows), 'rows; max residual',max(sol.rms_residuals),'Y99',Y99)
