"""Sequential MPI CBC campaign. Each invocation/continuation gets a fresh output directory."""
import argparse
import csv
import datetime
import fcntl
import hashlib
import json
import math
import os
from pathlib import Path
import shlex
import signal
import subprocess
import sys
import time

from verify_package import sha256

ROOT = Path(__file__).resolve().parents[1]
STATIONS = [0.0, 0.13841843855582028, 0.31885676024465742]


def read_config(path):
    values = {}
    for line in path.read_text(encoding='utf-8-sig').splitlines():
        line = line.split('#', 1)[0].strip()
        if line and '=' in line:
            key, value = line.split('=', 1)
            values[key.strip()] = value.strip()
    return values


def write_config(path, values):
    path.write_text('# Generated by run_campaign.py; paths are absolute for strict restart.\n' +
                    ''.join(f'{key} = {value}\n' for key, value in values.items()), encoding='utf-8')


def atomic_json(path, data):
    temp = path.with_suffix('.tmp')
    temp.write_text(json.dumps(data, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')
    temp.replace(path)


def timestamp():
    return datetime.datetime.now(datetime.timezone.utc).isoformat()


def save_state(results, state):
    state['updated_utc'] = timestamp()
    atomic_json(results / 'campaign_state.json', state)
    with (results / 'summary.csv').open('w', newline='', encoding='utf-8') as stream:
        writer = csv.writer(stream)
        writer.writerow(['case', 'status', 'attempts', 'returncode', 'reason', 'phase', 'time', 'checkpoint'])
        for name, item in state['cases'].items():
            last = (item.get('attempts') or [{}])[-1]
            writer.writerow([name, item['status'], len(item.get('attempts', [])),
                             last.get('returncode', ''), last.get('reason', ''),
                             last.get('phase', ''), last.get('time', ''), last.get('checkpoint', '')])


def latest_checkpoint(output, case):
    # Production checkpoints take precedence over preparation, regardless of mtime.
    for path in [output / f'{case}.checkpoint.latest.cgns',
                 output / 'preparation' / f'{case}-preparation.checkpoint.latest.cgns']:
        if path.is_file() and path.stat().st_size > 0:
            return path.resolve()
    return None


def inspect_output(output, case):
    for phase, directory, prefix in [('production', output, case),
                                     ('preparation', output / 'preparation', case + '-preparation')]:
        manifests = sorted(directory.glob(prefix + '.manifest.r*.txt'))
        if manifests:
            manifest = read_config(manifests[-1])
            manifest['phase'] = phase
            metadata = directory / f'{case}_hit_metadata.txt'
            manifest['hit_phase'] = read_config(metadata).get('phase', '') if metadata.exists() else ''
            return manifest
    return {'phase': 'unknown', 'stop_reason': 'missing_manifest'}


def production_complete(returncode, info, target):
    try:
        reached = math.isclose(float(info.get('time', 'nan')), target, rel_tol=1e-8, abs_tol=1e-10)
    except ValueError:
        reached = False
    return (returncode == 0 and info.get('phase') == 'production' and
            info.get('hit_phase') == 'production' and
            info.get('stop_reason') == 'physical_time_reached' and reached)


def sampled_stations(results, item, case, required):
    seen = set()
    for attempt in item.get('attempts', []):
        path = results / attempt['segment'] / 'output' / f'{case}_hit_history.csv'
        if path.exists():
            with path.open(encoding='utf-8') as stream:
                for row in csv.DictReader(stream):
                    value = float(row['time'])
                    for station in required:
                        if math.isclose(value, station, rel_tol=1e-8, abs_tol=1e-10):
                            seen.add(station)
    return len(seen) == len(required)


def campaign_identity(campaign, binary, mode):
    h = hashlib.sha256()
    h.update(mode.encode())
    for path in [ROOT / 'campaign.json', binary] + [ROOT / c['config'] for c in campaign['cases']]:
        h.update(path.name.encode())
        h.update(sha256(path).encode())
    for path in sorted((ROOT / 'inputs').rglob('*')):
        if path.is_file():
            h.update(path.relative_to(ROOT).as_posix().encode())
            h.update(sha256(path).encode())
    return h.hexdigest()


def make_config(base, output, mode, checkpoint=None, wall_seconds=0):
    values = read_config(base)
    for key in ['mesh.path', 'hit.spectrum_file']:
        values[key] = str((base.parent / values[key]).resolve())
    values['output.directory'] = str(output.resolve())
    values['output.allow_existing'] = 'false'
    values['run.max_wall_time'] = str(wall_seconds)
    if mode == 'smoke':
        values.update({'mesh.path': str(ROOT / 'inputs/grids/hit16.cgns'), 'hit.n': '16',
                       'hit.preparation.time': '0.001', 'hit.preparation.max_steps': '30',
                       'run.t_end': '0.001', 'run.max_steps': '30',
                       'hit.statistics.end': '0.001', 'hit.sample_times': '0,0.001',
                       'hit.sample_every_steps': '1', 'hit.write_every_samples': '1',
                       'output.field.explicit_times': '0,0.001',
                       'output.checkpoint.every_time': '0.0005',
                       'output.checkpoint.explicit_times': '0,0.001',
                       'output.history.every_steps': '1', 'output.statistics.every_steps': '1'})
    if checkpoint:
        values['restart.path'] = str(checkpoint.resolve())
        values['restart.mode'] = 'strict'
    return values


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--np', type=int, default=8, help='MPI ranks for each case (default 8)')
    for n in [32, 64, 128]:
        parser.add_argument(f'--np{n}', type=int, help=f'Override ranks for {n}^3 cases')
    parser.add_argument('--launcher', default='mpiexec', help='MPI launcher executable, e.g. mpiexec or srun')
    parser.add_argument('--launcher-arg', action='append', default=[], help='Repeat; use --launcher-arg=--flag')
    parser.add_argument('--binary', type=Path, default=ROOT / 'build/wcns_run')
    parser.add_argument('--results', type=Path, help='Output tree; use the same tree to resume')
    parser.add_argument('--case', action='append', help='Run only specified case ID(s), repeatable')
    parser.add_argument('--job-seconds', type=float, default=0, help='Total budget for THIS invocation; 0 unlimited')
    parser.add_argument('--checkpoint-margin', type=float, default=300, help='Reserve seconds for exit/checkpoint I/O')
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument('--smoke', action='store_true', help='9 short 16^3 workflow checks; NOT production results')
    modes.add_argument('--dry-run', action='store_true', help='Actual grid configuration/initialization check; no time stepping')
    parser.add_argument('--retry-failed', action='store_true', help='Retry failed cases FROM INITIALIZATION, keeping old attempts')
    args = parser.parse_args()
    if any(x is not None and x < 1 for x in [args.np, args.np32, args.np64, args.np128]):
        parser.error('MPI rank counts must be positive')
    if args.job_seconds < 0 or args.checkpoint_margin < 0:
        parser.error('Time budgets must be nonnegative')
    return args


def run(args):
    started = time.monotonic()
    mode = 'smoke' if args.smoke else 'dry-run' if args.dry_run else 'production'
    results = (args.results or ROOT / ('results' if mode == 'production' else 'results_' + mode)).resolve()
    results.mkdir(parents=True, exist_ok=True)
    # OS lock releases even on abnormal Python exit. Prevent simultaneous writers/runs.
    lock = (results / '.campaign.lock').open('a')
    try:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError:
        raise SystemExit('Another campaign process holds ' + str(results))
    campaign = json.loads((ROOT / 'campaign.json').read_text(encoding='utf-8'))
    unknown = set(args.case or []) - {c['id'] for c in campaign['cases']}
    if unknown:
        raise SystemExit('Unknown case ID(s): ' + ', '.join(sorted(unknown)))
    binary = args.binary.resolve()
    identity = campaign_identity(campaign, binary, mode)
    state_path = results / 'campaign_state.json'
    if state_path.exists():
        state = json.loads(state_path.read_text(encoding='utf-8'))
        if state['identity'] != identity or state['package_root'] != str(ROOT):
            raise SystemExit('Input/binary/package path changed. Restore it for strict resume, or use a new --results directory.')
    else:
        if any(results.glob('*/segment-*')):
            raise SystemExit('Segment directories exist without campaign_state.json; use a new --results directory.')
        state = {'schema_version': 1, 'identity': identity, 'package_root': str(ROOT), 'mode': mode,
                 'created_utc': timestamp(), 'binary_sha256': sha256(binary),
                 'cases': {c['id']: {'status': 'not_started', 'attempts': []} for c in campaign['cases']}}
    active = {'process': None, 'interrupted': False}

    def stop(signum, _frame):
        active['interrupted'] = True
        proc = active['process']
        if proc and proc.poll() is None:
            # Best effort; launcher behavior varies. Wall budget is the preferred graceful stop.
            try:
                os.killpg(proc.pid, signum)
            except ProcessLookupError:
                pass

    signal.signal(signal.SIGINT, stop)
    signal.signal(signal.SIGTERM, stop)
    save_state(results, state)
    for case in campaign['cases']:
        name = case['id']
        if args.case and name not in args.case:
            continue
        item = state['cases'][name]
        if item['status'] in ['complete', 'validated']:
            print(f'SKIP {name}: {item["status"]}', flush=True)
            continue
        if item['status'] == 'failed' and not args.retry_failed:
            print(f'SKIP {name}: failed; inspect logs, use --retry-failed for a fresh attempt', flush=True)
            continue
        budget = 0
        if args.job_seconds:
            budget = args.job_seconds - (time.monotonic() - started) - args.checkpoint_margin
            if budget <= 1:
                print('Job budget exhausted; re-run the same command to continue.', flush=True)
                return 2
        if active['interrupted']:
            return 2
        checkpoint = None
        if item['status'] in ['pending', 'running']:
            for old in reversed(item['attempts']):
                checkpoint = latest_checkpoint(results / old['segment'] / 'output', name)
                if checkpoint:
                    break
        segment = Path(name) / f'segment-{len(item["attempts"]) + 1:04d}'
        directory = results / segment
        directory.mkdir(parents=True, exist_ok=False)
        values = make_config(ROOT / case['config'], directory / 'output', mode, checkpoint, budget)
        write_config(directory / 'config.wcns', values)
        np = getattr(args, 'np' + str(case['n'])) or args.np
        command = [args.launcher] + args.launcher_arg + ['-n', str(np), str(binary), '--config', str(directory / 'config.wcns')]
        if mode == 'dry-run':
            command.append('--dry-run')
        attempt = {'segment': segment.as_posix(), 'started_utc': timestamp(), 'mpi_ranks': np,
                   'command': command, 'restart_from': str(checkpoint) if checkpoint else ''}
        item['attempts'].append(attempt)
        item['status'] = 'running'
        save_state(results, state)
        print(f'START {name}: mode={mode}, ranks={np}, resume={bool(checkpoint)}, log={directory / "run.log"}', flush=True)
        with (directory / 'run.log').open('w', encoding='utf-8') as stream:
            stream.write(shlex.join(command) + '\n')
            stream.flush()
            try:
                active['process'] = subprocess.Popen(command, cwd=ROOT, stdout=stream, stderr=subprocess.STDOUT,
                                                      start_new_session=True)
                code = active['process'].wait()
            except OSError as error:
                stream.write(str(error) + '\n')
                code = 127
            finally:
                active['process'] = None
        info = inspect_output(directory / 'output', name)
        cp = latest_checkpoint(directory / 'output', name)
        attempt.update({'finished_utc': timestamp(), 'returncode': code, 'reason': info['stop_reason'],
                        'phase': info['phase'], 'time': info.get('time', ''), 'checkpoint': str(cp) if cp else ''})
        stations = [0.0, 0.001] if mode == 'smoke' else STATIONS
        if mode == 'dry-run' and code == 0:
            item['status'] = 'validated'
            attempt['reason'] = 'dry_run_only'
        elif production_complete(code, info, float(values['run.t_end'])):
            item['status'] = 'complete' if sampled_stations(results, item, name, stations) else 'failed'
            if item['status'] == 'failed':
                attempt['reason'] = 'missing_reference_station_samples'
        elif code == 2 or active['interrupted']:
            item['status'] = 'pending'
        else:
            item['status'] = 'failed'
        save_state(results, state)
        print(f'END {name}: {item["status"]}; exit={code}; {attempt["reason"]}; phase={info["phase"]}; t={info.get("time", "?")}', flush=True)
        if item['status'] == 'pending':
            print('Campaign paused. Re-run to resume; maximum_steps requires investigating/increasing the cap first.', flush=True)
            return 2
    selected = [v for k, v in state['cases'].items() if not args.case or k in args.case]
    return 0 if all(v['status'] in ['complete', 'validated'] for v in selected) else 1


if __name__ == '__main__':
    sys.exit(run(parse_args()))
